### PR TITLE
:sparkles: fix `package.json` and add icon to extension

### PR DESCRIPTION
**Pull request by AucaCoyan**
Hi! I like this `hjson` format
I would like to improve the extension by adding an icon and updating `package.json`

If you have any questions, shoot me!

### CODE REVIEW

**Comment by mkacct** [comment]
Is there any particular reason this ended up closed? These were some of the changes I came here to propose…

**Comment by AucaCoyan** [comment]
Yes, I thought the project was unmaintained in September 2023, because at that time the last commit was in January 2022.
Interesting is that the first commit after 9/23 was on November 2023, and then after that the last 2 commit happened this year.
Sadly this project has huge periods of time in which it's stays dormant (imo, time is subjective)

**Comment by AucaCoyan** [comment]
Feel free to copy all the code and open a new PR with the changes. Change as much as you like! no need to cite me as an author 👌

**Comment by trobro** [comment]
Sorry about the dormancy, @mkacct I can help you merge if you create a PR. But I don't use VS Code myself, so I don't know if merging is enough, or if some upload to a repository for VS Code is needed?

**Comment by mkacct** [comment]
@trobro  Yeah, any changes have to be deployed by someone with access to publish as the VS Marketplace publisher "laktak" (either using `vsce publish` or by uploading the VSIX directly to the publisher management portal).

I originally just meant to comment in support of the addition of an extension icon. (The extension looks a bit out of place with no icon, but that seems more like something to be directly addressed by the owners…)

**Comment by laktak** [comment]
>  or if some upload to a repository for VS Code is needed?

@trobro at the moment a manual upload is required - I don't run tests but if someone can confirm that a pr works (see #14) then it's not a problem to do the release.

**Pull request closed without merging**
